[versions]
kotlin = "2.1.0"
kotest = "5.9.1"
ktor = "3.0.1"

[libraries]
azure-digital-twins = { module = "com.azure:azure-digitaltwins-core", version = "1.4.0" }
azure-identity = { module = "com.azure:azure-identity", version = "1.14.2" }
azure-signalr = { module = "com.microsoft.signalr:signalr", version = "8.0.11" }
ditto-wot-model = { module = "org.eclipse.ditto:ditto-wot-model", version = "3.6.2" }
jena = { module = "org.apache.jena:apache-jena-libs", version = "5.2.0" }
kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-assertions-ktor = { module = "io.kotest.extensions:kotest-assertions-ktor", version = "2.0.0" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.9.0" }
kotlin-scripting = { module = "org.jetbrains.kotlin:kotlin-scripting-jsr223", version.ref = "kotlin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.7.3" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-content-negotiation-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-engine-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
logging = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.0" }
sl4j = { module = "org.slf4j:slf4j-simple", version = "2.0.16" }

[bundles]
kotlin-testing = [
    "kotest-junit5",
    "kotest-assertions-core",
    "kotest-assertions-core-jvm",
    "kotest-assertions-ktor",
    "ktor-server-test-host",
]

[plugins]
dokka = { id ="org.jetbrains.dokka", version = "1.9.20" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.70.2" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }